//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESDWaveformVerifierTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESDWaveformVerifierTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.000000002963,-0.782256
        ///-0.000000002953,-0.753707
        ///-0.000000002943,-0.670159
        ///-0.000000002933,-0.526995
        ///-0.000000002923,-0.335130
        ///-0.000000002913,-0.116815
        ///-0.000000002903,0.106118
        ///-0.000000002893,0.302182
        ///-0.000000002883,0.445766
        ///-0.000000002873,0.529313
        ///-0.000000002863,0.554084
        ///-0.000000002853,0.528054
        ///-0.000000002843,0.466758
        ///-0.000000002833,0.387829
        ///-0.000000002823,0.295465
        ///-0.000000002813,0.193444
        ///-0.000000002803,0.085127
        ///-0.000000002793,-0.020672
        ///-0.000000002783,-0.120593
        ///-0.0000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CDM_Large_Neg_1000V {
            get {
                return ResourceManager.GetString("CDM_Large_Neg_1000V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.000000002957,0.031138
        ///-0.000000002947,0.026205
        ///-0.000000002937,0.020328
        ///-0.000000002927,0.012351
        ///-0.000000002917,0.001015
        ///-0.000000002907,-0.011790
        ///-0.000000002897,-0.023965
        ///-0.000000002887,-0.037085
        ///-0.000000002877,-0.051150
        ///-0.000000002867,-0.064585
        ///-0.000000002857,-0.074661
        ///-0.000000002847,-0.082113
        ///-0.000000002837,-0.085262
        ///-0.000000002827,-0.083372
        ///-0.000000002817,-0.074766
        ///-0.000000002807,-0.059442
        ///-0.000000002797,-0.036455
        ///-0.000000002787,-0.006437
        ///-0.000000002777,0.027150
        ///-0.00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CDM_Large_Pos_0250V {
            get {
                return ResourceManager.GetString("CDM_Large_Pos_0250V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.000000002969,-0.118536
        ///-0.000000002959,-0.053441
        ///-0.000000002949,0.008163
        ///-0.000000002939,0.062284
        ///-0.000000002929,0.107677
        ///-0.000000002919,0.144090
        ///-0.000000002909,0.171774
        ///-0.000000002899,0.183995
        ///-0.000000002889,0.177511
        ///-0.000000002879,0.146834
        ///-0.000000002869,0.091964
        ///-0.000000002859,0.017141
        ///-0.000000002849,-0.065911
        ///-0.000000002839,-0.144225
        ///-0.000000002829,-0.206827
        ///-0.000000002819,-0.246233
        ///-0.000000002809,-0.265438
        ///-0.000000002799,-0.271673
        ///-0.000000002789,-0.273917
        ///-0.000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CDM_Small_Neg_1000V {
            get {
                return ResourceManager.GetString("CDM_Small_Neg_1000V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.0000000029736,0.128988
        ///-0.0000000029636,0.113400
        ///-0.0000000029536,0.096876
        ///-0.0000000029436,0.079480
        ///-0.0000000029336,0.059029
        ///-0.0000000029236,0.034026
        ///-0.0000000029136,0.005967
        ///-0.0000000029036,-0.023401
        ///-0.0000000028936,-0.051646
        ///-0.0000000028836,-0.075776
        ///-0.0000000028736,-0.090741
        ///-0.0000000028636,-0.097288
        ///-0.0000000028536,-0.095542
        ///-0.0000000028436,-0.086189
        ///-0.0000000028336,-0.068855
        ///-0.0000000028236,-0.046720
        ///-0.0000000028136,-0.020034
        ///-0.0000000028036,0.010581
        ///-0.0000000027936 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CDM_Small_Pos_0250V {
            get {
                return ResourceManager.GetString("CDM_Small_Pos_0250V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.0000000029387,-0.231423
        ///-0.0000000029187,-0.207382
        ///-0.0000000028987,-0.181838
        ///-0.0000000028787,-0.157045
        ///-0.0000000028587,-0.133755
        ///-0.0000000028387,-0.113470
        ///-0.0000000028187,-0.097693
        ///-0.0000000027987,-0.084170
        ///-0.0000000027787,-0.076657
        ///-0.0000000027587,-0.072900
        ///-0.0000000027387,-0.072900
        ///-0.0000000027187,-0.075905
        ///-0.0000000026987,-0.080413
        ///-0.0000000026787,-0.085672
        ///-0.0000000026587,-0.090931
        ///-0.0000000026387,-0.094688
        ///-0.0000000026187,-0.097693
        ///-0.0000000025987,-0.096942
        ///-0.00000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CDM_Small_Pos_1000V_PosUndershoot {
            get {
                return ResourceManager.GetString("CDM_Small_Pos_1000V_PosUndershoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.000000117060,0.000839
        ///-0.000000116660,0.000839
        ///-0.000000116260,0.000839
        ///-0.000000115860,0.000839
        ///-0.000000115460,0.000839
        ///-0.000000115060,0.000839
        ///-0.000000114660,0.014707
        ///-0.000000114260,-0.040765
        ///-0.000000113860,-0.026897
        ///-0.000000113460,0.014707
        ///-0.000000113060,0.000839
        ///-0.000000112660,0.000839
        ///-0.000000112260,0.000839
        ///-0.000000111860,0.000839
        ///-0.000000111460,-0.013029
        ///-0.000000111060,0.000839
        ///-0.000000110660,0.014707
        ///-0.000000110260,-0.013029
        ///-0.000000109860,0.014707
        ///-0.00000010946 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HBM_0Ohm_Neg_8000V {
            get {
                return ResourceManager.GetString("HBM_0Ohm_Neg_8000V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.000000116643,0.000627
        ///-0.000000116243,-0.000229
        ///-0.000000115843,-0.000229
        ///-0.000000115443,-0.001086
        ///-0.000000115043,0.001483
        ///-0.000000114643,-0.000229
        ///-0.000000114243,-0.001942
        ///-0.000000113843,0.000627
        ///-0.000000113443,-0.000229
        ///-0.000000113043,0.000627
        ///-0.000000112643,-0.000229
        ///-0.000000112243,0.000627
        ///-0.000000111843,0.000627
        ///-0.000000111443,-0.001086
        ///-0.000000111043,0.001483
        ///-0.000000110643,-0.001942
        ///-0.000000110243,-0.001942
        ///-0.000000109843,-0.000229
        ///-0.000000109443,-0.000229
        ///-0.000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HBM_0Ohm_Pos_0500V {
            get {
                return ResourceManager.GetString("HBM_0Ohm_Pos_0500V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.000000116830,0.003141
        ///-0.000000116430,-0.003118
        ///-0.000000116030,0.003141
        ///-0.000000115630,0.003141
        ///-0.000000115230,-0.006247
        ///-0.000000114830,0.000011
        ///-0.000000114430,-0.006247
        ///-0.000000114030,0.000011
        ///-0.000000113630,0.006270
        ///-0.000000113230,-0.006247
        ///-0.000000112830,0.006270
        ///-0.000000112430,-0.003118
        ///-0.000000112030,0.000011
        ///-0.000000111630,0.000011
        ///-0.000000111230,0.000011
        ///-0.000000110830,0.009399
        ///-0.000000110430,0.000011
        ///-0.000000110030,-0.003118
        ///-0.000000109630,0.000011
        ///-0.000000109 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HBM_500Ohm_Neg_4000V {
            get {
                return ResourceManager.GetString("HBM_500Ohm_Neg_4000V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.000000116205,0.001757
        ///-0.000000115805,-0.000615
        ///-0.000000115405,-0.000615
        ///-0.000000115005,0.000176
        ///-0.000000114605,-0.000615
        ///-0.000000114205,0.000176
        ///-0.000000113805,-0.000615
        ///-0.000000113405,0.000176
        ///-0.000000113005,0.000966
        ///-0.000000112605,0.000176
        ///-0.000000112205,0.000176
        ///-0.000000111805,-0.001405
        ///-0.000000111405,-0.001405
        ///-0.000000111005,0.000966
        ///-0.000000110605,0.001757
        ///-0.000000110205,0.000176
        ///-0.000000109805,-0.000615
        ///-0.000000109405,-0.001405
        ///-0.000000109005,0.000966
        ///-0.0000001 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HBM_500Ohm_Pos_1000V {
            get {
                return ResourceManager.GetString("HBM_500Ohm_Pos_1000V", resourceCulture);
            }
        }
    }
}
